# hledger update just needs the following resources:
# cronjob - run the application on a schedule
# configmap - we need git config so we can git commit
# secret - we need ssh keys so we can clone

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hledger-update
spec:
  schedule: "00 14 * * FRI"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            # we need SSH key for git cloning
            - name: ssh-key-volume
              secret:
                secretName: ssh-key
              # any other config we need
            - name: config
              configMap:
                name: configs
          containers:
            # the main app container needs ssh keys so it can clone
            # we also need .gitconfig so we can commit
            - name: app
              image: hledger-update:latest
              imagePullPolicy: Never
              volumeMounts:
                - name: ssh-key-volume
                  readOnly: true
                  mountPath: "/home/app/ssh-keys"
                - name: config
                  mountPath: "/conf/"
              env:
                - name: PLAID_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: plaid-secrets
                      key: client_id
                - name: PLAID_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: plaid-secrets
                      key: secret
                - name: PLAID_PUBLIC_KEY
                  valueFrom:
                    secretKeyRef:
                      name: plaid-secrets
                      key: public_key
                - name: PLAID_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: plaid-secrets
                      key: access_token

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
  .gitconfig: "[user]\n\tname = Nick Dujay\n\temail = nickdujay@gmail.com\n[push]\n\tdefault = simple\n"

