# we need a cron job + git config

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hledger-update
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: hledger-update
        spec:
          volumes:
          # we need SSH key for git cloning
          - name: ssh-key-volume
            secret:
              secretName: ssh-key
          # any other config we need
          - name: config
            configMap:
              name: configs
          containers:
          # the main app container needs ssh keys so it can clone
          # we also need .gitconfig so we can commit
          - name: app
            image: hledger-update:latest
            imagePullPolicy: Never
            volumeMounts:
            - name: ssh-key-volume
              readOnly: true
              mountPath: "/home/app/ssh-keys"
            - name: config
              mountPath: /conf/
          restartPolicy: OnFailure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
  .gitconfig: "[user]\n\tname = Nick Dujay\n\temail = nickdujay@gmail.com\n[push]\n\tdefault
    = simple\n"
